version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    image: web:latest
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    container_name: web

  postgres:
    image: postgres:15.6
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    container_name: postgres

  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: redis
    
  celery-beat:
    image: web:latest
    command: celery -A django_project beat -l info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - redis
      - web
    container_name: celery-beat

  celery-worker:
    image: web:latest
    command: celery -A django_project worker -l info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - redis
      - web
    container_name: celery-worker

  flower:
    image: mher/flower:0.9.7
    command: ['flower', '--broker=redis://redis:6379/1', '--port=5555']
    ports:
      - 5557:5555
    depends_on:
      - redis
    container_name: flower

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 8025:8025
    container_name: mailhog

  
volumes:
  postgres_data:
